<script lang="ts">
import { Options, Vue } from "vue-class-component";
import { useMeterStore } from "@/stores/meters";
import { MeterService } from "@/services/MeterService";
import { MeterReadingService } from "@/services/MeterReadingService";
import type { IMeter } from "@/domain/IMeter";

@Options({
  components: {},
  props: {
    meter: Object as () => IMeter,
  },
})
export default class Meter extends Vue {
  meterStore = useMeterStore();
  meterService = new MeterService();
  meterReadingService = new MeterReadingService();
  meter!: IMeter;
  value!: number;

  errorMessage: Array<string> | null | undefined = null;

  mounted() {
    console.log(this.meter.meterReadings?.length);

    if (
      this.meter.meterReadings != null &&
      this.meter.meterReadings.length !== 0
    ) {
      this.value = this.meter.meterReadings[0].value;
    }
  }

  async addReading(): Promise<void> {
    const res = await this.meterReadingService.add({
      meterId: this.meter.id!,
      value: this.value,
      date: new Date().toDateString(),
      autoGenerated: false,
    });

    if (res.status >= 300) {
      this.errorMessage = res.errorMessage;
      console.log(res);
    } else {
      this.errorMessage = null;
      this.meter.meterReadings = await this.meterReadingService.getAll(
        this.meter.id
      );
    }
  }
}
</script>

<template>
  <div
    v-if="errorMessage != null"
    class="text-danger validation-summary-errors mt-3 text-center"
    data-valmsg-summary="true"
    data-valmsg-replace="true"
  >
    <ul v-for="error of errorMessage">
      <li>{{ error }}</li>
    </ul>
  </div>
  <div class="container d-flex justify-content-center mb-3 h-100">
    <div class="col-8 h-100">
      <div class="card h-100 border-secondary justify-content-center">
        <div class="card-body">
          <h3 class="card-title text-center mb-1">
            {{ meter?.meterType?.name }}
          </h3>
          <div class="text-center mb-1">
            <small>({{ meter?.meterNumber }})</small>
          </div>
          <div class="row align-items-center justify-content-center">
            <div class="form-floating col-auto">
              <input v-model="value" class="form-control" type="number" />
              <label>Reading</label>
            </div>
            <div class="col-auto">
              <h5>{{ meter.meterType?.measuringUnit?.symbol }}</h5>
            </div>
            <div class="col-auto">
              <input
                @click="addReading()"
                type="submit"
                value="Add reading"
                class="btn btn-outline-secondary btn-lg"
              />
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
