version: '3.8'

networks:
    outside:
      driver: bridge
      ipam:
        driver: default
        config:
          - subnet: 192.168.0.0/24

services:
  yhistu-postgres:
    container_name: yhistu-postgres
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
        
    logging:
      options:
        max-size: 10m
        max-file: '3'
          
    ports:
      - "5432:5432"
    volumes:
      - yhistu-postgres-volume:/var/lib/postgresql/data
      
    networks:
      default:
      outside: 
        ipv4_address: 192.168.0.22
        
volumes:
  yhistu-postgres-volume:
          